### PR TITLE
Added ability to include a common glsl file

### PR DESCRIPTION
**Pull request by pflannery**
I've managed to emulate the shadertoy common pass. 

I've setup a new definition called "#iCommon". I didnt want to affect any existing protocols so I've added a new protocol called "glsl://". Full example:  `#iCommon glsl://./common/blobby-common.glsl`
Let me know what your happy with for define and protocol naming covention.

I've added a demo called blobby. I've mutated it from https://www.shadertoy.com/view/ldBBRV. (I will remove the demo if you dont want it there)

The only thing I haven't done is compile the common file on its own. The workaround is to manually add a "void main() {}" temporarily when working in the common file.

### CODE REVIEW

**Comment by Malacath-92** [comment]
Sorry guys, been moving this week so I didn't get to look at this earlier.

I tested this for a bit and I'm not sure if this really is equivalent to the shadertoy common code.
In shadertoy you would specify one common code and all shaders in your pipeline will use it. However here we will need to specify the "common" code for each shader in our pipeline. I.e. when I add a shader to your blobby example that samples from blobby.glsl by using rotate:
```#iChannel0 buf://./blobby.glsl
#iCommon glsl://./common/blobby-common.glsl

void main() {
    vec2 uv = gl_FragCoord.xy / iResolution.xy;

    uv = rotate(uv - 0.5, iTime * 0.05) + 0.5;

    vec4 originalBlobby = texture(iChannel0, uv);
    gl_FragColor = originalBlobby;
}```
then I need to specify iCommon.

I think a better name for it would be a plain old _#include_. Then a user knows that this is local to a shader and they can include multiple files to their liking.

What do you think?

**Comment by Malacath-92** [comment]
Also, I should mention, that this breaks line numbers on error printouts. If we add a check to allow includes and other # definitions only before everything else then we can just subtract the included file's line number. Otherwise we need to do line mapping, and I bet we don't want that  😃 
I can fix the line numbers myself if you prefer.

**Comment by pflannery** [comment]
@Malacath-92 

> Also, I should mention, that this breaks line numbers on error printouts

Fixed.

**Comment by pflannery** [comment]
@Malacath-92 

> And if we rename it #include then we don't need to specify "glsl://" either.

I've renamed to "#include" but it would take some rework on path resolution if we change the schema to something like "#include './path/common.glsl'. 
Any rework would also still need to handle error file linking. 
So for now I have left the protocol part. Its easy to switch it to `file://` if you want?

**Comment by pflannery** [comment]
>I tested this for a bit and I'm not sure if this really is equivalent to the shadertoy common code.
In shadertoy you would specify one common code and all shaders in your pipeline will use it. 

We could have a presumed common filepath like './common.glsl' (overridable in settings) and include with every glsl file launched in the workspace?

However buffers aren't presumed to be buffer0, buffer1...etc which gives flexible file naming to the user. So having this flexibility could be useful for common too.

**Comment by pflannery** [comment]
@Malacath-92 
Having thought some more on this maybe there is way that we could include the common code in each dependant. 

main.glsl:

```glsl
#include file://./common.glsl
#iChannel0 buf://./bufferA.glsl
void main() {}
```

In the example above bufferA.glsl would automatically include common.glsl.

This would save us having to write "#include file://./common.glsl" in every dependant of main.glsl.

**Comment by Malacath-92** [comment]
> I've renamed to "#include" but it would take some rework on path resolution if we change the schema to something like "#include './path/common.glsl'.
> Any rework would also still need to handle error file linking.
> So for now I have left the protocol part. Its easy to switch it to `file://` if you want?
I think this is reasonable for now. We can rethink/rework this still before the next release.

> In the example above bufferA.glsl would automatically include common.glsl.
If we do this then we lose one thing that the extensions is imho superior compared to the online version: currently every shader that is used in a pipeline is self-contained, i.e. if you use it in _#iChannelN buf://..._ then it has to work on it's own as well, else it is ill-formed. By injecting code (in this example from a _#include_) from the top-level shader that is currently running we lose this, unless you insert that code by hand (in this case _#include_ the same file). In that sense I personally would be hesitant to do this.

I prefer your suggestion of having
1. proper includes (in future version those should probably also work correctly with nesting)
2. and an implicit _common.glsl_ (as you said exposed in settings.json).
A question arising for this though is that of where this common.glsl is searched for. In the same folder as the top-level shader? In the same folder as each respective shader?

**Comment by Malacath-92** [comment]
I think the best choice for this PR is to merge is as a _#include_ feature and determine how to continue with the _common_ feature somewhere else.
What do you think @pflannery ?

**Comment by pflannery** [comment]
I agree with merge now and figure the rest out somewhere else.

> proper includes (in future version those should probably also work correctly with nesting)

Yes shorter syntax i.e."#include './common.glsl'" and deep nesting would be cool.

> and an implicit common.glsl (as you said exposed in settings.json).

My personal preference is explicitly specifing includes in each dependant.

**Comment by Malacath-92** [comment]
> My personal preference is explicitly specifing includes in each dependant.
Alright, that looks like we found common ground. When porting multipass shaders from shadertoy.com there anyways is some manual labour involved, this will be an additional step which allows us to keep the shaders clean of more magic  :)

**Pull request merged**
