### PR TITLE
Audio input and others

### PR DESCRIPTION
**Pull request by Malacath-92**
I'm sorry for this huge PR, it's not very professional. I mainly wanted to include audio input but got sidetracked so many times to do various improvements. Some things need more discussion than others:
- [x] I deprecated some things, meaning they are still available but might get removed in future versions. My reasoning for deprecation is that there are more natural alternatives or less volatile alternatives. Deprecated things are inputs in package.json, specifying inputs/includes in shaders with our "custom protocols" (instead now its inferred) and specifying inputs/includes without quotation marks.
- [x] Fixed several bugs, see README.md.
- [x] Added audio input from local sources.
- [x] Did not get audio input from remote sources to work unproblematically.
- [x] Added small update message to inform users when their extension is updated.
- [x] Persist state (e.g. time, mouse and keyboard) across compilations.
- [ ] Noticed very rare bug that causes audio to be broken/not start, where the broken state is quite uncomfortable to hear. Unfortunately I can not reproduce it reliably and have experienced it only twice during testing. Hopefully you can find it and reproduce it. Otherwise I don't think it's a good to hand this to users, if at all we should potentially make it opt-in with that warning.
- [x] Major refactoring of the extension into multiple files.
- [x] Two new dependencies are introduced, `mime` and `compare-versions`.
- [x] Despite major changes, shaders from the last patch should still be compatible with this version.

Please take all the time in the world to think about these things and tick them off if you think we found a consensus.

### CODE REVIEW

**Comment by stevensona** [comment]
Okay this is pretty massive. Looks to be nearly a complete rewrite.

Haven't gone through the whole thing yet. Just kind of curious if this is still "work in progress" or pretty much ready to go?

**Comment by Malacath-92** [comment]
I wouldn't say it's a complete rewrite, the main logic as well as the flow of data are intact, I only moved bits out to other files/classes to compartmentalise the whole thing a bit more.
In terms of features this is good to go, besides the audio bug that I would do something about depending how best to solve it.
Other than that, the code can always be improved of course, I'm not a ts pro. 

I'm really sorry it's so huge, so I understand if it takes a lot more time than usually. If you can't see an end I could also invest some time to split off features into multiple PRs. But we could still have the discussion regarding the viability of some of those here.

**Comment by stevensona** [comment]
No need to break up the PR--just need some time to go through. Refactoring is good.

**Comment by stevensona** [comment]
Okay now I see why having them broken up would've been nice. But no worries--it'll just take a bit longer to get everything in.

I looked through your changelist and then marked off the obvious stuff. By the way, the improvements you made, specifically with regards to the overall organization, look very good. This extension started as a result of a 2-3 hour experiment on a weekend, but there's no reason for the code quality to reflect that.

Right now my main concern is with the audio glitch that is "uncomfortable to hear". I have been unable to reproduce it on my local so I'm curious what it is you mean by that? In general, I don't mind releasing a semi-working feature as long as users are aware it's "going to get better", which you have noted in the readme and notes.

So anyway, overall looks great. Just need some more clarification on the audio glitch.

**Comment by Malacath-92** [comment]
So the audio bug is difficult to explain for me, I'm sure there's a word for it that I don't know.
When the audio is loaded, instead if playing the expected audio, it would play a "random" waveform that is maybe 20-50ms long on repeat for maybe half a second and then stay silent. The glitched audio is maybe a bit louder than the expected audio would be, but it is not insane. A possible workaround could also be to ramp the volume up over the first second or so, but that is far from a good solution imho.
After some more testing I get the best chances of proccing this bug by:
- running on battery,
- loading large audio files (e.g. Beethovens 5th),
- quickly recompiling the shader loading different files.

I'll try to gather some more information or an example of what it's like from somewhere.

**Comment by Malacath-92** [comment]
Fixed the two new issues #49 and #50
Feel free to expand on the description on includes in the README
I haven't had time yet to learn more about the audio issue unfortunately.

**Comment by Malacath-92** [comment]
I tested a couple of times more and I could never reproduce the bug I mentioned in the PR. Should we tag the feature as experimental and disable it by default?

**Comment by stevensona** [comment]
I would say "yes" we want to tag as experimental, but don't think there is a need to disable by default due to the fact that it is a new feature that no one would be using prior to this. What are your thoughts?

**Comment by Malacath-92** [comment]
I only suggested that because if the bug exists, it might be better if user have to make a concious decision to use it, being aware that they might encounter it. Of course using the audio is a concious decision one way or another, but it's difficult to get a warning to users in time if it is enabled by default.

**Comment by stevensona** [comment]
Fair enough. The feature will need to be explicitly enabled.

**Comment by Malacath-92** [comment]
Just pushed two commits for this.

**Comment by stevensona** [comment]
Again thanks for this massive effort. Glad to finally get it released 👍

**Pull request merged**
