### PR TITLE
Fullfill feature requests & Publish in CI

### LINKED ISSUE #107: Comments between 'mainImage' function name and body break compilation
I don't need them, but it's not easy to find where error is
Not working:
```
void mainImage() /**/ {
}
```
```
void mainImage() //
{
}
```

### LINKED ISSUE #111: Default texture wrap mode set to clamp, not repeat as on shadertoy.com
On an simple shadertoy.com example: 
```
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    // Normalized pixel coordinates (from 0 to 1)
    vec2 uv = fragCoord/iResolution.xy + iTime;

    // Output to screen
    fragColor = texture(iChannel0, uv);
}
```
The texture just is repeated. But it is not the same case for the "GLSL Preview". The texture is only one time and get out of the screen :P

### LINKED ISSUE #114: Can not control filter and wrap mode for buffer input
https://www.shadertoy.com/view/XsyGzz

grafik

grafik

### LINKED ISSUE #115: [Feature Request] Disable automatic recompilation
It would be nice to make the auto-recompile feature optional. Having your computer constantly watching file changes and triggering recompilation isn't always desirable, especially if you're on battery power, your laptop chassis is the heat sink, you're working on a shader that takes inexplicably long to compile (written by some one else, of course 😉.)

I imagine the most flexible approach would be to add some command palette option to allow users to switch between having the preview recompile when they've changed the previewed file, only when they've _saved_ the file, or only manually via some other command/a "recompile" button over the preview next to play/pause.

### PR DESCRIPTION
**Pull request by Malacath-92**
Closes #107 
Closes #111 
Closes #114 
Closes #115 

I also added a "Publish" step in the Github Actions CI but I don't think that will auto-bump the version number. So it would require a commit with a manual version number bump and then tagging that commit as a release. It would also require setting up a secret. I closes stuck to [this guide](https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions-automated-publishing) which also links to creating the secret. Not sure if this is feasible to use for simpler deploy of the extension or not, but you be the judge of that  :)

### CODE REVIEW

**Review by stevensona — APPROVED** [review]
LGTM.

I added the PAT and will give it a whirl. 👍

**Comment by stevensona** [comment]
Check out https://github.com/stevensona/shader-toy/actions/runs/314509974

It appears to be skipping the publish step, even with the release created. Feel free to play around. The PAT should be in place now, but nothing sticking out at me as to what is preventing publish step from running.

Going to go ahead and attempt a manual release.

**Comment by stevensona** [comment]
I screwed up back in July when I bumped the version to release the attribution fix but forgot to push the changes back up here. So I released your changes as 0.10.13. Apologies for that.

**Comment by Malacath-92** [comment]
I looked a bit closer into it and I think the issue is with having Publish in the same workflow as the tests. I'll try separating the Publish step into its own workflow, just need to figure out inter-workflow dependencies. But there's no urgency with this I would think  :)

**Pull request merged**
